Repository spectrocloud/cluster-api-provider-vsphere-static-ip, pull requests merged in 2020-12, with the labels that each got.

#21 Image path update
  Makefile
Labels: approved, lgtm, ok-to-test, size/XS

#20 fix the source for search domains
  go.mod
  pkg/ipam/metal3io/metal3io_ipam.go
Labels: approved, lgtm, size/XS

#23 Get VSphereMachine's nameservers/searchDomains from VsphereMachineTemplate, by default
  controllers/vspheremachine_controller.go
  pkg/ipam/metal3io/metal3io_ipam.go
  tests/integration/allocate_static_ip_func_test.go
  tests/integration/allocate_static_ip_test.go
  tests/integration/testenv/testdata.go
  tests/integration/testenv/testdata/capi_machinedeployment.yaml
  tests/integration/testenv/testdata/m3ipam_ip_pool.yaml
Labels: approved, lgtm, size/L
